nymea/nymea-plugins

debian/control, networkdetector/devicemonitor.cpp
On the new buster image, arping isn't installed. This causes the plugin to break completely and prevent it from marking devices as gone.
a) add a dependency to arping to make it work properly on buster
b) prevent it from breaking completely even on setups without arping (e.g. self compiled)
Yes, tested on a buster rpi4
No changes needed
No string changes
N/A
=> NetworkDetector: Improve packaging and error handling

usbrelay/rawhiddevicewatcher.cpp
=> UsbRelay: Fix initialization of udev device watcher if no matching device is connected

datetime/integrationplugindatetime.cpp, networkdetector/devicemonitor.cpp, shelly/integrationpluginshelly.cpp
=> Don't use API deprecated in Qt 5.14

tasmota/integrationplugintasmota.json
The channels are "POWER", "POWER0", "POWER1" etc... so they're
strings, not integers.
We could also use integers, however, that would require special handling
for the single channel (only "POWER" without number) on every publish,
this way we can do that just once in the setup and be done with it.
=> Tasmota: Fix wrong param types for channels

genericthings/integrationplugingenericthings.json, serialportcommander/integrationpluginserialportcommander.json, simulation/integrationpluginsimulation.json, tcpcommander/integrationplugintcpcommander.json, udpcommander/integrationpluginudpcommander.json
=> Fix some plugins that fail the new, more strict param validation

shelly/integrationpluginshelly.cpp
There's a crash when the mqtt channel is released twice if the shelly has poor wifi reception and network requests to it during the setup time out.
Not fixed yet. Adding some debug prints to understand in detail how that happens.
=> Shelly: Fix occational crash when setup times out

debian/control, debian/nymea-plugin-pushnotifications.install.in, nymea-plugins.pro, pushnotifications/README.md, pushnotifications/integrationpluginpushnotifications.cpp, pushnotifications/integrationpluginpushnotifications.h, pushnotifications/integrationpluginpushnotifications.json, pushnotifications/pushnotifications.pro, pushnotifications/translations/fdcea3b3-8d79-4fbb-8101-1ab45d71cedb-de.ts, pushnotifications/translations/fdcea3b3-8d79-4fbb-8101-1ab45d71cedb-en_US.ts
This plugin allows to send push notifications to nymea:app without the need to
go through nymea:cloud.
This is useful for users that prefer to not have a cloud account at all and
improves privacy and server costs as it cuts out one server hop of the messages.
Supported platforms:
* Android
* iOS
* UBPorts
=> New Plugin: PushNotifications

plugins.pri
=> Fix qmake warning message if plugin.pri isn't found

bose/soundtouchtypes.h, nuki/bluez/bluetoothmanager.cpp, sonos/integrationpluginsonos.cpp, tado/tado.h
Don't have a Nuki. If someone could test this.. Reasonably confident it didn't break anything though.
=> Nuki: Fix bad if clause guards

osdomotics/integrationpluginosdomotics.cpp
Old code would crash if the plugin fails to load and is destroyed before init() is called.
=> Osdomotics: Fix a crash if the plugin fails to load

mecelectronics/integrationpluginmecelectronics.json
Given that this plugin polls a REST api every second, and all those values will change every time for a wee bit, this plugin is quite heavy on the resources for no real use.
-> Enable adaptive filtering for voltage states which are jittering but never really change
-> Disable caching for all volatile states. This gets away with *a lot* of unneeded disk IO and also seems to be the more correct thing to do.
=> MecMeter: Optimize performance

somfytahoma/README.md, somfytahoma/integrationpluginsomfytahoma.cpp, somfytahoma/integrationpluginsomfytahoma.h, somfytahoma/integrationpluginsomfytahoma.json, somfytahoma/somfytahomarequests.cpp, somfytahoma/somfytahomarequests.h, somfytahoma/translations/4e8be1c1-daa8-4e21-9e85-b2372ab1a450-en_US.ts
This PR changes the somfytahoma plugin to directly connect to Somfy Tahoma Gateways without having to rely on the Somfy Tahoma cloud connection.
In order to activate this local API, users need to enable the so called 'Developer Mode' on their gateways. See https://developer.somfy.com/developer-mode. Existing plugin users will have to reconfigure the plugin.
The old cloud based access had several disadvantages:
- Somfy changed the login method that caused the old version of the plugin to disconnect after a few days.
- Somfy started to disconnect and block 3rd party applications that polled device updates too fast.
The local access now offers various advantages:
- We don't rely on an internet connection any more (except for initial access to the box) which should drastically improve …
=> somfytahoma: Use local connection "Somfy Developer Mode"

meross/integrationpluginmeross.cpp
The hostname resoving does not seem to work in all cases.
=> Meross: Also list devices with a Meross owned mac address

tplink/integrationplugintplink.cpp, tplink/integrationplugintplink.h
In very rare occations it seems to not send a reply which would
lock up the job queue.
=> TpLink: Add a timeout timer for jobs

systemmonitor/README.md, systemmonitor/integrationpluginsystemmonitor.cpp, systemmonitor/integrationpluginsystemmonitor.h, systemmonitor/integrationpluginsystemmonitor.json, systemmonitor/translations/908b4f18-dc0c-4940-a6f7-c0c01a2861b8-en_US.ts, systemmonitor/translations/b82bce59-59bf-48b3-b781-54a6f45800f3-en_US.ts
SystemMonitor: Extend plugin
Renames the old systemMonitor thingClass into processMonitor as that's
what it actually did and allow monitoring other processes, not just
nymead.
Adds a new thingClass named systemMonitor to allow fetching total
CPU, memory and Disk stats.
=> SystemMonitor: Add more process and system monitoring capabilites

somfytahoma/integrationpluginsomfytahoma.cpp
The assumption that all IO roller shutters support the
setClosureAndLinearSpeed action was incorrect, only the RS100 IO does.
In order to maximize compatibility, use setClosure instead.
For the moment this means RS100 IO motors don't move in silent mode
anymore until we find a solution to differentiate them from others.
Forum reference: https://forum.nymea.io/t/somfytahoma-plugin-questions/814/9
---
=> somfytahoma: Fix actions for roller shutters

fronius/integrationpluginfronius.cpp
=> Fronius: Fix a crash if the discovery times out

shelly/integrationpluginshelly.cpp, shelly/integrationpluginshelly.json
UDP multicast isn't properly working on some network setups
so we'll default to unicast by configuring our own IP to the
shelly. This has the downside that the Shelly device won't work
any more with other software or multiple nymea setups, so we'll
still allow choosing the multicast option in the setup params.
=> Shelly: Allow choosing between unicast and multicast CoIoT

wemo/README.md
changed Belkin wemo dead link to overview page
=> Wemo: Change link in Readme

aqi/integrationpluginaqi.json
The ordering of the interfaces is used by the app to determine best matches for a particular use case. The AQI plugin is most likely to be relevant for use cases regarding particulate matter measurement.
=> AQI: Reorder interfaces based on their relevancy

netatmo/integrationpluginnetatmo.cpp
=> Netatmo: fix OAuth2 credentials loading from api key provider

eq-3/integrationplugineq-3.cpp, eq-3/integrationplugineq-3.json, tado/integrationplugintado.cpp, tado/integrationplugintado.h, tado/integrationplugintado.json, tado/tado.cpp, tado/tado.h
The interface now distinguishes between states that are informative (read only) and ones that can be set.
=> EQ-3, Tado: Update thermostats windowOpenDetected states

evbox/evboxport.cpp, evbox/integrationpluginevbox.cpp
=> EVBox: Fix processing erraneous packets that still pass the CRC check and a double action finish() call

fronius/fronius.pro, fronius/froniusdiscovery.cpp, fronius/froniusdiscovery.h, fronius/froniussolarconnection.cpp, fronius/froniussolarconnection.h, fronius/integrationpluginfronius.cpp, fronius/integrationpluginfronius.h, fronius/integrationpluginfronius.json
This isn't good yet. Discovery needs to be reworked to properly detect the fronius api instead.
=> Fronius: Add precise discovery

shelly/integrationpluginshelly.cpp
This change is simply to make regexp case insensitive for discovery of Shelly Plus 1PM. This is necessary because some device show with only lower case. The change was done only for Shelly Plus 1PM, but it could make sense to do it for all the Shelly devices.
=> Shelly: Fix discovery for 1 Plus PM

mailnotification/smtpclient.cpp
The message body is already composed using a \r\n.\r\n at the end, and the actual sending process appended an extra one. While apparently the plugin was working with most mail servers, the double \r\n.\r\n at the end violates the spec and newer OpenSMTP servers are rejecting this.
=> MailNotification: Fix double mail ending

unifi/README.md
already prepared an update for the Unifi plugin containg the following changes:
- difference between Hardware and software-based controllers
- description of the port field and its different values
- made clear that only local users can login
please wait with publishing until the latest plugin with the described changes is in experimental and I could test it.
Thanks.
=> Update README.md Unifi Plugin

awattar/README.md, awattar/integrationpluginawattar.cpp, awattar/integrationpluginawattar.json
Allows to do stuff when ranking indicates the current slots is in top x for the day.
Also fixes a bug that the current value hasn't been taken into account when calculating averages/deviations
=> Awattar: Add a ranking state for simple use in rules

shelly/integrationpluginshelly.cpp, shelly/integrationpluginshelly.h
When shelly integration can't join the multicast group it begins spaming the log each 5s. With this commit it log the joining problem each 5s for the first Minute, after that each 10min.
=> Shelly: Improve debug logging when offline

everest/everest.cpp, everest/everest.h, everest/everestclient.cpp, everest/everestclient.h, everest/everestdiscovery.cpp, everest/everestdiscovery.h, everest/integrationplugineverest.cpp
=> EVerest: Autosetup connectors on localhost

keba/integrationpluginkeba.cpp, keba/integrationpluginkeba.h, keba/integrationpluginkeba.json, keba/kebadiscovery.cpp, keba/kebadiscovery.h
=> Keba: Update to networkdevice interface
