elgato/aveabulb.cpp
elgato/aveabulb.h
elgato/aveacolor.cpp
elgato/aveacolor.h
elgato/devicepluginelgato.cpp
elgato/devicepluginelgato.h
elgato/devicepluginelgato.json
elgato/elgato.pro

Revert "Fix avea plugin"

---

philipshue/devicepluginphilipshue.cpp
philipshue/hueremote.cpp

instead, always wait for the reply and mark it as gone if the
reply is bad

drop logic to mark hue as unreachable if it doesn't reply in time.

---

philipshue/devicepluginphilipshue.cpp
philipshue/devicepluginphilipshue.h
philipshue/devicepluginphilipshue.json
philipshue/huebridge.cpp
philipshue/huebridge.h

* adds support for color temperature lights
* fixed parsing of device type
* adds support for pairing a bulb using its serial number

update hue plugin

---

debian/control
debian/nymea-plugin-genericinterfaces.install.in
genericinterfaces/deviceplugingenericinterfaces.cpp
genericinterfaces/deviceplugingenericinterfaces.h
genericinterfaces/deviceplugingenericinterfaces.json
genericinterfaces/genericinterfaces.pro
genericinterfaces/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts
nymea-plugins.pro

Plug-in similar to generic elements but utilizing nymea interfaces

New plugin: generic interfaces

---

tcpcommander/README.md
tcpcommander/deviceplugintcpcommander.cpp
tcpcommander/deviceplugintcpcommander.h
tcpcommander/deviceplugintcpcommander.json
tcpcommander/tcpcommander.pro
tcpcommander/tcpserver.cpp
tcpcommander/tcpserver.h
tcpcommander/tcpsocket.cpp
tcpcommander/tcpsocket.h

* extended Readme
* changed vendor to nymea
* fixed input and output
* removed string comparison (now done in rule engine)

TcpCommander: Fixed input and output device class 

---

flowercare/README.md
flowercare/devicepluginflowercare.cpp
flowercare/devicepluginflowercare.json
flowercare/translations/74e2106a-3407-4e89-a27a-1c890d78bee7-de.ts
flowercare/translations/74e2106a-3407-4e89-a27a-1c890d78bee7-en_US.ts

FlowerCare: Add a refresh rate setting

---

senic/nuimo.cpp

No Nuimo available: @Boernsman or @simonseres please test and approve (or request changes).
N/A
N/A
N/A

Nuimo: Make it work with Bluez 5.48 (except battery service)

---

debian/control

Anel: Add anel plugin to main plugin package

---

philipshue/huemotionsensor.cpp

Yes, tested with indoor motion sensor, compared with various lux measurement apps on the mobile phone. Values match nicely now.
No changes in there
No changes there
N/A

PhilipsHue: Fix light intensity conversion to lux for the motion sensor

---

philipshue/devicepluginphilipshue.cpp

PhilipsHue: Fix the timeout setting

---

tasmota/README.md
tasmota/deviceplugintasmota.cpp
tasmota/deviceplugintasmota.h
tasmota/deviceplugintasmota.json

Y
Y (Well, tested with a 2CH switch but from logs it should be ok, forum users can test 4CH devices)
Y
N/A
N/A

Tasmota: Add Blinds support

---

anel/README.md
awattar/README.md
coinmarketcap/README.md
datetime/README.md
denon/README.md
elgato/README.md
philipshue/README.md

Various Plugins: Spelling fixes in README files

---

daylightsensor/README.md

DaylightSensor: Update README.md

---

dweetio/README.md

dweet.io: Update README

---

debian/rules

Packaging: Fix dpkg clean target

---

debian/changelog
debian/control
networkdetector/devicepluginnetworkdetector.cpp
simulation/devicepluginsimulation.cpp
simulation/devicepluginsimulation.json

Simulation: Add a simulated barcode scanner device

---

tasmota/README.md

Changed Sonoff-Tasmota name to `Tasmota`, the official name starting from release 7.x. and added more info. 
New link for documentation, the internal wiki was replaced.
Thanks,
Federico Leoni
Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
* Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to …

Update Tasmota readme

---

eq-3/deviceplugineq-3.cpp
eq-3/deviceplugineq-3.json
eq-3/maxcubediscovery.cpp

EQ-3: Fix connection to MAX! cube

---

bose/README.md
bose/devicepluginbose.cpp
bose/devicepluginbose.h
bose/devicepluginbose.json
bose/soundtouch.cpp
bose/soundtouch.h
bose/soundtouchtypes.h

Bose SoundTouch: Fix actions and add source browsing

---

kodi/devicepluginkodi.cpp

Kodi: Skip link-local IPv6 addresses

---

debian/control
debian/nymea-plugin-tplink.install.in
nymea-plugins.pro
tplink/README.md
tplink/deviceplugintplink.cpp
tplink/deviceplugintplink.h
tplink/deviceplugintplink.json
tplink/tplink.pro
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-de.ts
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-en_US.ts

New Plugin: tp-link Kasa

---

debian/changelog
texasinstruments/deviceplugintexasinstruments.json

HectoPascal -> MilliBar
It's the same anyways, but the interface requires MilliBar

TexasInstruments: Fix pressure unit for sensortag

---

debian/control
debian/nymea-plugin-openuv.install.in
nymea-plugins.pro
openuv/README.md
openuv/devicepluginopenuv.cpp
openuv/devicepluginopenuv.h
openuv/devicepluginopenuv.json
openuv/openuv.pro
openuv/translations/9b7d9cc8-77df-4197-a6fc-8a365747a3b1-en_US.ts

New Plug-In: OpenUV

---

httpcommander/devicepluginhttpcommander.cpp

y
* Did you test the changes on hardware, if not (e.g. abse
nce of required hardware), please mention a person to confirm it has been tested.
n @Boernsman please
N/A
N/A
N/A

HttpCommander: Build with more strict compiler settings

---

debian/control
debian/nymea-plugin-nanoleaf.install.in
nanoleaf/README.md
nanoleaf/devicepluginnanoleaf.cpp
nanoleaf/devicepluginnanoleaf.h
nanoleaf/devicepluginnanoleaf.json
nanoleaf/nanoleaf.cpp
nanoleaf/nanoleaf.h
nanoleaf/nanoleaf.pro
nanoleaf/translations/360867ec-1594-498d-8182-fbab1fe17489-en_US.ts
nymea-plugins.pro

New Plugin: Nanoleaf

---

boblight/bobchannel.cpp
boblight/bobclient.cpp
boblight/bobclient.h
boblight/devicepluginboblight.cpp

Boblight: Fix behavior if color is changed very fast

---

debian/control
debian/nymea-plugin-tado.install.in
nymea-plugins.pro
philipshue/README.md
tado/README.md
tado/deviceplugintado.cpp
tado/deviceplugintado.h
tado/deviceplugintado.json
tado/tado.cpp
tado/tado.h
tado/tado.pro
tado/translations/b4f2d2ee-50bb-4786-b7f5-261fed204fa5-en_US.ts

New plugin: Tado

---

debian/changelog
tplink/README.md
tplink/deviceplugintplink.cpp
tplink/deviceplugintplink.h
tplink/deviceplugintplink.json
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-de.ts
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-en_US.ts

TP-Link: Add support for HS100, HS103, HS105, HS200 and KP100

---

shelly/README.md
shelly/devicepluginshelly.cpp
shelly/devicepluginshelly.h
shelly/devicepluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en.ts

Shelly: Add 2.5, 1PM, Dimmer, RGBW2 and Plug/PlugS

---

bose/devicepluginbose.cpp
bose/devicepluginbose.h
bose/devicepluginbose.json
bose/soundtouch.cpp
bose/soundtouch.h
bose/translations/472a3f24-b05c-49b3-ad9a-dfda608b6760-en_US.ts

Bose: Add support for presets

---

avahimonitor/integrationpluginavahimonitor.cpp
avahimonitor/integrationpluginavahimonitor.json

Avahi Monitor: added address and port

---

tuya/integrationplugintuya.cpp
tuya/integrationplugintuya.h

Tuya: Fix devId parameter for blinds

---

shelly/integrationpluginshelly.cpp

@simonseres Please report back

Shelly: Add switch device to Shelly Dimmer

---

tado/integrationplugintado.cpp
tado/integrationplugintado.h
tado/integrationplugintado.json
tado/tado.cpp
tado/tado.h
tado/translations/b4f2d2ee-50bb-4786-b7f5-261fed204fa5-de.ts
tado/translations/b4f2d2ee-50bb-4786-b7f5-261fed204fa5-de_DE.ts

Tado: Add heating interface

---

sonos/sonos.cpp

Sonos Plug-In: Make playlist load & start right away

---

tado/integrationplugintado.cpp
tado/integrationplugintado.h
tado/tado.cpp
tado/tado.h

Tado Plug-In: Fixed crash during thing pairing

---

debian/changelog

Bump version to 0.22

---

genericthings/genericthings.pro
genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.h
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

Generic Things: Add venetian blind

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for the Shelly Dimmer 2

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
simulation/integrationpluginsimulation.json
tplink/integrationplugintplink.json
tuya/integrationplugintuya.json
wemo/integrationpluginwemo.json

Make use of generic IO support in smart plugs

---

awattar/README.md
awattar/integrationpluginawattar.cpp
awattar/integrationpluginawattar.h
awattar/integrationpluginawattar.json
awattar/translations/9c261c33-d44e-461e-8ec1-68803cb73f12-de.ts
awattar/translations/9c261c33-d44e-461e-8ec1-68803cb73f12-en_US.ts

Awattar: The token is not needed any more for AT

---

debian/changelog

Bump version to 0.23

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.h
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

Generic things: Add extended smart meter

---

philipshue/hueremote.cpp

Hue: Don't falsely emit button presses at startup

---

anel/integrationpluginanel.cpp
anel/integrationpluginanel.json

AnelElektronik: Fix actions and add generic IO types

---

onewire/README.md
onewire/integrationpluginonewire.cpp
onewire/integrationpluginonewire.json
onewire/onewire.pro
onewire/owfs.cpp
onewire/owfs.h
onewire/translations/2c697fb7-0645-466d-9cb9-aa1922c85bee-de.ts
onewire/w1.cpp
onewire/w1.h

OneWire PlugIn: Add W1 support

---

philipshue/huelight.cpp
philipshue/huelight.h

Hue: Don't set invalid states to the hue color light

---

nanoleaf/integrationpluginnanoleaf.cpp
nanoleaf/integrationpluginnanoleaf.h
nanoleaf/integrationpluginnanoleaf.json
nanoleaf/nanoleaf.pro
nanoleaf/translations/360867ec-1594-498d-8182-fbab1fe17489-de.ts
nanoleaf/translations/360867ec-1594-498d-8182-fbab1fe17489-en_US.ts

Nanoleaf: Fix IPv6

---

aqi/integrationpluginaqi.cpp

AirQualityIndex: Fix custom apikey

---

onewire/integrationpluginonewire.cpp
onewire/integrationpluginonewire.h

OneWire: Fixed W1 temperature sensor setup

---

tuya/integrationplugintuya.cpp
tuya/integrationplugintuya.h

Tuya: Poll api less frequently to adhere to new API rate limits

---

aqi/README.md
aqi/airqualityindex.cpp
aqi/airqualityindex.h
aqi/integrationpluginaqi.cpp
aqi/integrationpluginaqi.h
aqi/integrationpluginaqi.json
aqi/translations/57d69b76-4d2d-41ec-bef6-949a79ffbe6b-de.ts
aqi/translations/57d69b76-4d2d-41ec-bef6-949a79ffbe6b-en_US.ts

AQI: Added API key provider

---

mqttclient/mqttclient.pro

MQTTClient: Fix linking with more restrictive flags

---

openweathermap/integrationpluginopenweathermap.cpp
openweathermap/integrationpluginopenweathermap.h
openweathermap/integrationpluginopenweathermap.json
openweathermap/translations/bc6af567-2338-41d5-aac1-462dec6e4783-de.ts
openweathermap/translations/bc6af567-2338-41d5-aac1-462dec6e4783-en_US.ts

OpenWeatherMap: Use api key provider api

---

bluos/integrationpluginbluos.h

BluOS: Fix undefined reference

---

udpcommander/integrationpluginudpcommander.cpp

UDP Commander: Fix processing of multiple UDP datagrams in one go

---

solarlog/integrationpluginsolarlog.json

SolarLog: Fix units in json

---

simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.json
simulation/translations/b7368429-e312-4c82-9eab-e1cd996e43d6-en_US.ts

Simulation plug-in: Added door/windows contact sensor

---

shelly/integrationpluginshelly.json

Shelly: Clean up a copy/paste error in the plugin JSON

---

eq-3/integrationplugineq-3.json
flowercare/integrationpluginflowercare.json
philipshue/integrationpluginphilipshue.json
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts
tasmota/integrationplugintasmota.cpp
tasmota/integrationplugintasmota.h
tasmota/integrationplugintasmota.json
tasmota/translations/d136e0c0-0cbf-4731-aabb-b2201088d6cb-en_US.ts
tplink/integrationplugintplink.cpp
tplink/integrationplugintplink.h
tplink/integrationplugintplink.json
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-de.ts
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-en_US.ts

Make use of the wirelessconnectable interface across relevant plugins

---

philipshue/huebridge.cpp
philipshue/huebridge.h
philipshue/huedevice.cpp
philipshue/huedevice.h
philipshue/huelight.cpp
philipshue/huelight.h
philipshue/huemotionsensor.cpp
philipshue/huemotionsensor.h
philipshue/hueremote.cpp
philipshue/hueremote.h
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.h

PhilipsHue: Fix automatic rediscovery of the bridge if it changes IP

---

tado/integrationplugintado.cpp
tado/integrationplugintado.json
tado/tado.cpp
tado/tado.h
tado/translations/b4f2d2ee-50bb-4786-b7f5-261fed204fa5-de.ts
tado/translations/b4f2d2ee-50bb-4786-b7f5-261fed204fa5-en_US.ts

Tado: Added dynamic API credential optaining

---

philipshue/huemotionsensor.cpp

Hue: Fix motionsensor flickering with low intervals

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.h
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

GenericThings: Add a generic thermostat

---

simulation/integrationpluginsimulation.json

Simulated things: Sensors add ioType

---

onewire/integrationpluginonewire.json

Onewire: Add iotype

---

netatmo/integrationpluginnetatmo.cpp
netatmo/integrationpluginnetatmo.h
netatmo/integrationpluginnetatmo.json
netatmo/netatmobasestation.cpp
netatmo/netatmobasestation.h
netatmo/netatmooutdoormodule.cpp
netatmo/netatmooutdoormodule.h
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-cs.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-da.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-de.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-en_US.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-es.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-fr.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-it.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-nl.ts
netatmo/translations/69d14951-0c02-4877-bcef-dffdf48b7ccb-pt.ts

Netatmo: Add api key provider and custom api plugin settings

---

bose/integrationpluginbose.cpp
bose/integrationpluginbose.h
bose/integrationpluginbose.json
bose/translations/472a3f24-b05c-49b3-ad9a-dfda608b6760-de.ts

Bose SoundTouch: Add alert interface and api key provider

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for the Shelly Button 1

---

debian/changelog

0.25 version bump

---

kodi/kodi.cpp
kodi/kodi.h

Kodi: Fix a small leak when removing kodi things

---

simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.h
simulation/integrationpluginsimulation.json

Simulation: Add audio player thing

---

doorbird/doorbird.cpp
doorbird/doorbird.h
doorbird/integrationplugindoorbird.cpp
doorbird/integrationplugindoorbird.h
doorbird/integrationplugindoorbird.json

Doorbird: Improve setup and reconfiguration

---

eq-3/eqivabluetooth.cpp
eq-3/eqivabluetooth.h
eq-3/integrationplugineq-3.cpp
eq-3/integrationplugineq-3.json
genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.json
tado/integrationplugintado.json

Thermostats: Adjust to new thermostat interface

---

philipshue/README.md
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.h
philipshue/integrationpluginphilipshue.json
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

PhilipsHue: Add better support for the Hue Smart plug

---

zigbeegeneric/integrationpluginzigbeegeneric.cpp
zigbeegeneric/integrationpluginzigbeegeneric.h

ZigbeeGeneric: Extend generic power socket

---

flowercare/integrationpluginflowercare.json

FlowerCare: Add missing unit to batteryLevel state

---

shelly/integrationpluginshelly.json
systemmonitor/integrationpluginsystemmonitor.json
tplink/integrationplugintplink.json

Adjust to new logging and filter options

---

eq-3/eqivabluetooth.cpp
eq-3/eqivabluetooth.h
eq-3/integrationplugineq-3.cpp
eq-3/integrationplugineq-3.json
genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.json
tado/integrationplugintado.json
zigbeelumi/integrationpluginzigbeelumi.json

Simulation: Add simulated venetian blinds

---

zigbeephilipshue/README.md
zigbeephilipshue/integrationpluginzigbeephilipshue.cpp
zigbeephilipshue/integrationpluginzigbeephilipshue.h
zigbeephilipshue/integrationpluginzigbeephilipshue.json
zigbeephilipshue/translations/0ca340b7-061a-42e6-ab7d-d7b4fd235d02-en_US.ts

ZigbeePhilipsHue: Add support for the Hue Smart button

---

debian/control
keba/README.md
keba/discovery.cpp
keba/integrationpluginkeba.cpp
keba/integrationpluginkeba.h
keba/integrationpluginkeba.json
keba/keba.pro
keba/kecontact.cpp
keba/kecontact.h
keba/kecontactdatalayer.cpp
keba/kecontactdatalayer.h
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-de.ts
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-en_US.ts

Keba: Rework plugin

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

GenericThings: Add a generic door/window sensor

---

gpio/integrationplugingpio.cpp
gpio/integrationplugingpio.h
gpio/integrationplugingpio.json

That doesn't make sense in most cases...

GPIO: Remove button interface from GPIO input

---

fronius/froniusstorage.cpp

Fronius: Storage battery critical only when not charging

---

tasmota/integrationplugintasmota.cpp
tasmota/integrationplugintasmota.json
tasmota/translations/d136e0c0-0cbf-4731-aabb-b2201088d6cb-en_US.ts

Tasmota: Add support for the gneric I/O mechanism

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for shelly i3 

---

simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.json

Simulation:  EV Charger update interface

---

tuya/integrationplugintuya.cpp
tuya/integrationplugintuya.h

Fixes: https://github.com/nymea/nymea/issues/384

Tuya: Poll the cloud even less frequently to avoid rate limits

---

tplink/README.md
tplink/integrationplugintplink.cpp
tplink/integrationplugintplink.h
tplink/integrationplugintplink.json
tplink/sampledata/HS105-TCP.txt
tplink/sampledata/HS105-UDP.txt
tplink/sampledata/HS110-TCP.txt
tplink/sampledata/HS110-UDP.txt
tplink/sampledata/HS200-TCP.txt
tplink/sampledata/HS200-UDP.txt
tplink/sampledata/HS300-TCP.txt
tplink/sampledata/HS300-UDP.txt
tplink/sampledata/simulator.cpp
tplink/sampledata/simulator.pro
tplink/tplink.pro
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-de.ts
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-en_US.ts

TP-Link: Add support for TP-Link Kasa Power Strip HS300

---

genericthings/integrationplugingenericthings.json

GenericThings: Add unit Percentage to input value

---

shelly/integrationpluginshelly.cpp

Shelly: Don't complete setup for childs when the parent setup fails

---

anel/anel.pro
anel/discovery.cpp
anel/discovery.h
anel/integrationpluginanel.cpp
anel/integrationpluginanel.h
anel/integrationpluginanel.json
anel/translations/7a3e5b64-20e4-42bd-b86b-989b84afc22a-en_US.ts

Anel: Automatically update configuration when the IP changes

---

tuya/README.md
tuya/integrationplugintuya.cpp
tuya/integrationplugintuya.h
tuya/integrationplugintuya.json
tuya/translations/405643b3-22ec-4a36-9808-e8b1405b01c9-en_US.ts

Tuya: Add light device support

---

denon/heos.cpp
denon/heos.h
denon/integrationplugindenon.cpp
denon/integrationplugindenon.h
denon/integrationplugindenon.json
denon/translations/cd758269-dbbb-4ef0-80ab-48bd9a8a2765-de.ts
denon/translations/cd758269-dbbb-4ef0-80ab-48bd9a8a2765-en_US.ts

Denon: Added rediscovery on IP change

---

zigbeelumi/integrationpluginzigbeelumi.cpp

ZigbeeLumi: Fix pressure for Lumi sensors

---

neatobotvac/integrationpluginneatobotvac.py

Added code to display boundary info in log -- it doesn't "do" anything yet but displays the string rbtBoundData to analyse how to integrate this into the start cleaning operation (tested on robot)

neatobotvac: obtain map boundary info

---

nuki/bluez/bluetoothgattcharacteristic.cpp
nuki/bluez/bluetoothgattcharacteristic.h
nuki/bluez/bluetoothgattdescriptor.cpp
nuki/bluez/bluetoothmanager.cpp
nuki/integrationpluginnuki.cpp
nuki/integrationpluginnuki.h
nuki/nuki.cpp
nuki/nuki.h
nuki/nukiauthenticator.cpp
nuki/nukiauthenticator.h
nuki/nukicontroller.cpp
nuki/nukicontroller.h
nuki/nukiutils.h

Nuki: Add support for Nuki 2.0

---

flowercare/integrationpluginflowercare.json
fronius/froniusstorage.cpp
fronius/integrationpluginfronius.json
netatmo/integrationpluginnetatmo.json
philipshue/integrationpluginphilipshue.json
senic/integrationpluginsenic.json
shelly/integrationpluginshelly.json
simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.json
zigbeegeneric/integrationpluginzigbeegeneric.json
zigbeephilipshue/integrationpluginzigbeephilipshue.json
zigbeetradfri/integrationpluginzigbeetradfri.json

Update to new battery interface

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

GenericThings: Add a generic presense sensor

---

somfytahoma/integrationpluginsomfytahoma.cpp
somfytahoma/integrationpluginsomfytahoma.h
somfytahoma/somfytahomarequests.cpp
somfytahoma/somfytahomarequests.h

This fixes the login with passwords that contain HTML special chars.

somfytahoma: Fix credential encoding

---

zigbeegeneric/README.md
zigbeegeneric/integrationpluginzigbeegeneric.cpp
zigbeegeneric/integrationpluginzigbeegeneric.h
zigbeegeneric/integrationpluginzigbeegeneric.json
zigbeegeneric/translations/6a4343be-9fd6-4015-9ff5-38542651c534-en_US.ts

ZigbeeGeneric: Add support for ZigBee door/window sensors

---

telegram/README.md
telegram/integrationplugintelegram.cpp
telegram/integrationplugintelegram.h

Telegram: Fix small cosmetic issue during setup and improve readme

---

somfytahoma/README.md
somfytahoma/integrationpluginsomfytahoma.cpp
somfytahoma/integrationpluginsomfytahoma.json
somfytahoma/translations/4e8be1c1-daa8-4e21-9e85-b2372ab1a450-en_US.ts

somfytahoma: Add support for awnings and lights

---

flowercare/integrationpluginflowercare.json
fronius/froniusstorage.cpp
fronius/integrationpluginfronius.json
netatmo/integrationpluginnetatmo.json
philipshue/integrationpluginphilipshue.json
senic/integrationpluginsenic.json
shelly/integrationpluginshelly.json
simulation/integrationpluginsimulation.cpp
simulation/integrationpluginsimulation.h
simulation/integrationpluginsimulation.json
simulation/translations/b7368429-e312-4c82-9eab-e1cd996e43d6-de.ts
zigbeegeneric/integrationpluginzigbeegeneric.json
zigbeephilipshue/integrationpluginzigbeephilipshue.json
zigbeetradfri/integrationpluginzigbeetradfri.json

Simulation: Add a cleaning robot simulation

---

tasmota/integrationplugintasmota.cpp
tasmota/integrationplugintasmota.h
tasmota/integrationplugintasmota.json
tasmota/translations/d136e0c0-0cbf-4731-aabb-b2201088d6cb-en_US.ts

Tasmota: Add support for the Sonoff Dimmer

---

onewire/README.md
onewire/integrationpluginonewire.cpp
onewire/integrationpluginonewire.h
onewire/integrationpluginonewire.json
onewire/owfs.cpp
onewire/owfs.h
onewire/translations/2c697fb7-0645-466d-9cb9-aa1922c85bee-de.ts
onewire/translations/2c697fb7-0645-466d-9cb9-aa1922c85bee-en_US.ts

OneWire Plugin: Add temperature and humidity sensor

---

openweathermap/integrationpluginopenweathermap.json
openweathermap/translations/bc6af567-2338-41d5-aac1-462dec6e4783-de.ts
openweathermap/translations/bc6af567-2338-41d5-aac1-462dec6e4783-en_US.ts

Openweathermap: Update labels to be in line with other plugins

---

shelly/shelly.pro
tasmota/tasmota.pro

Use pkgconfig to find nymea-mqtt

---

mqttclient/integrationpluginmqttclient.cpp

Make includes more flexible

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Tested by dossidos on the forum. There might be an issue with power reporting (even though according to the docs I can't see why as it's the same for all shelly devices) but I haven't been able to get good enough debug reports.

Shelly: Add support for the Shelly motion sensor

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.h
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

GenericThings: Add a generic battery thing

---

fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.h

Fronius: Fix timer clean up on things removed and code cleaning

---

wakeonlan/integrationpluginwakeonlan.cpp
wakeonlan/integrationpluginwakeonlan.h
wakeonlan/integrationpluginwakeonlan.json
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-cs.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-da.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-de.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-en_US.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-es.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-fr.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-it.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-nl.ts
wakeonlan/translations/b5a87848-de56-451e-84a6-edd26ad4958f-pt.ts

WakeOnLan: Add network device discovery 

---

tplink/README.md
tplink/integrationplugintplink.cpp
tplink/integrationplugintplink.json
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-de.ts
tplink/translations/024ff2e3-30df-44a1-9c8d-63cc416f1fb8-en_US.ts

Tested by community user in forum

TP-Link Kasa: Add KP105

---

tado/tado.h

Tado: Fix login url

---

homeconnect/meta.json
neatobotvac/meta.json

Fix neatobotvac and homeconnect categories

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

GenericThings: Added O2, PH, ORP, CO and flammable gas generic sensors

---

philipshue/README.md
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.json
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

added support for on/off light

Philips Hue: Add support for on/off light

---

philipshue/README.md
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.json
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

Philips hue: Add dimmer switch v2

---

philipshue/README.md
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.json
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

Philips Hue - add support for Friends of Hue switch and Wall switch module

---

tplink/integrationplugintplink.json

TP-Link: Fix smart meter interfaces

---

shelly/integrationpluginshelly.cpp

Shelly: Add second switch for the Shelly 1L

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts

Shelly: Add generic IO states for shelly 2.5

---

fronius/froniuslogger.cpp
fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.h
fronius/integrationpluginfronius.json
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-de.ts
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-en_US.ts

Fronius: Add network discovery and broken API version check

---

debian/control
debian/nymea-plugin-mcp3008.install.in
i2cdevices/integrationplugini2cdevices.json
mcp3008/README.md
mcp3008/integrationpluginmcp3008.json
mcp3008/integrationpluginmcp3008.py
mcp3008/mcp3008.pro
mcp3008/meta.json
mcp3008/requirements.txt
nymea-plugins.pro

New Plugin: MCP3008 SPI DAC

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for settings for the Shelly I3

---

goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.json
goecharger/translations/a1dfca21-3f41-4a67-bc8c-c8b333411bd9-en_US.ts

Add plugedIn interface state for goE-Charger

---

neatobotvac/integrationpluginneatobotvac.py

Neato Botvac: Use nymea plugintimer

---

keba/integrationpluginkeba.cpp
keba/integrationpluginkeba.json
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-de.ts
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-en_US.ts

Keba: Add plugged in interface state and translate different states

---

genericelements/integrationplugingenericelements.cpp
genericelements/integrationplugingenericelements.json
genericelements/translations/6e22161e-39b7-4416-8623-39e730721efb-de.ts
genericelements/translations/6e22161e-39b7-4416-8623-39e730721efb-en_US.ts

GenericElements: Make use of interfaces in generic elements and add trigger button

---

zigbeedevelco/integrationpluginzigbeedevelco.json

ZigbeeDevelco: Use adaptive filter for sensor values

---

keba/integrationpluginkeba.cpp

Keba: Filter discovered devices by mac address vendor and not by hostname

---

goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.h
goecharger/integrationplugingoecharger.json
goecharger/translations/a1dfca21-3f41-4a67-bc8c-c8b333411bd9-en_US.ts

goecharger: extend states and make mqtt optional

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json

Shelly: Fix switch settings for second channel

---

zigbeephilipshue/integrationpluginzigbeephilipshue.cpp
zigbeephilipshue/integrationpluginzigbeephilipshue.h
zigbeephilipshue/integrationpluginzigbeephilipshue.json

ZigbeePhilipsHue: Use manufacturer specific remote commands

---

goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.json
goecharger/translations/a1dfca21-3f41-4a67-bc8c-c8b333411bd9-en_US.ts

goECharger: set limit for charging current and update to new interface definitions

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.h
genericthings/integrationplugingenericthings.json

GenericThings: Update generic SG-Ready thing and add heat pump interfaces

---

genericthings/integrationplugingenericthings.cpp
genericthings/integrationplugingenericthings.json
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-de.ts
genericthings/translations/b3188696-2585-4806-bf98-30ab576ce5c8-en_US.ts

Generic things: Add a generic water level sensor

---

tplink/README.md
tplink/integrationplugintplink.cpp

TP-Link Kasa: Add support for the KP115 switch

---

debian/control
debian/nymea-plugin-garadget.install.in
garadget/README.md
garadget/garadget.pro
garadget/garadget.svg
garadget/integrationplugingaradget.cpp
garadget/integrationplugingaradget.h
garadget/integrationplugingaradget.json
garadget/meta.json
garadget/translations/476781af-ad41-423b-b9bb-f308f2aff339-en_US.ts
nymea-plugins.pro

New plugin: Garadget

---

i2cdevices/README.md
i2cdevices/i2cdevices.pro
i2cdevices/ina219.cpp
i2cdevices/ina219.h
i2cdevices/integrationplugini2cdevices.cpp
i2cdevices/integrationplugini2cdevices.h
i2cdevices/integrationplugini2cdevices.json
i2cdevices/translations/7318d45b-2eed-472c-ae08-aad56db31e28-de.ts
i2cdevices/translations/7318d45b-2eed-472c-ae08-aad56db31e28-en_US.ts

I2CDevices: Add support for the INA219 energy meter

---

fronius/froniusinverter.cpp
fronius/froniusmeter.cpp
fronius/froniusstorage.cpp
fronius/froniusstorage.h
fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.json
fronius/meta.json
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-de.ts
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-en_US.ts

Fronius: Update to latest interface requirements and add providedInterfaces 

---

philipshue/integrationpluginphilipshue.json

Hue: Add new providedInterfaces property with light and powersocket to bridge

---

shelly/integrationpluginshelly.json

Shelly: Remove adaptive filtering

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json

Shelly: Add support for the shelly vintage bulb

---

keba/meta.json

Keba: Add category to meta.json

---

tempo/meta.json

Tempo: Fix meta.json

---

mcp3008/meta.json

MCP3008: Fix meta.json

---

mecelectronics/meta.json

mecElectronics: Fix meta.json

---

philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.h
philipshue/integrationpluginphilipshue.json
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

PhilipsHue: Improve discovery and error handling

---

shelly/integrationpluginshelly.json

Shelly: Don't cache volatile states

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for Shelly EM

---

solarlog/integrationpluginsolarlog.cpp
solarlog/integrationpluginsolarlog.json

SolarLog: Fix currentPower state and disable caching for volatile states

---

bluos/integrationpluginbluos.cpp

BluOS: Fix eventTypeId -> stateTypeId typo

---

keba/integrationpluginkeba.cpp
keba/integrationpluginkeba.json

Keba: Fix eventTypes -> stateTypes typo and uncache volatile states

---

mqttclient/integrationpluginmqttclient.cpp
mqttclient/integrationpluginmqttclient.h
mqttclient/integrationpluginmqttclient.json

MQTT client: Add more parameters to thing class (for SSL and will)

---

debian/control

Neato Botvac: Fix dependencies

---

sma/integrationpluginsma.json

SMA: Add default value for sma sunny webbox thing param #528

---

goecharger/README.md
goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.h

go-eCharger: Handle reconfigure for MQTT and queue HTTP requests 

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h

Shelly: Try to reconfigure MQTT on disconnected shellies

---

somfytahoma/integrationpluginsomfytahoma.json

SomfyTahoma: Fix min/max values as per interface

---

dht/integrationplugindht.py

DHT: Properly clean up pluginTimer when all things are gone

---

shelly/integrationpluginshelly.cpp

Shelly: Fix switch settings (button mode and reverse)

---

mecelectronics/integrationpluginmecelectronics.cpp
mecelectronics/translations/5853701d-a335-4282-892f-f23670269505-de.ts
mecelectronics/translations/5853701d-a335-4282-892f-f23670269505-en_US.ts

MecElectronics: Return proper error code on wrong authentication

---

onewire/integrationpluginonewire.cpp
onewire/integrationpluginonewire.h
onewire/owfs.cpp
onewire/owfs.h

OneWire: Make owfs more robust against occational read errors

---

tcpcommander/integrationplugintcpcommander.cpp
tcpcommander/integrationplugintcpcommander.json
tcpcommander/tcpserver.cpp
tcpcommander/tcpserver.h

TcpCommander: Add TCP server broadcast functionality to send data to all connected clients

---

kodi/integrationpluginkodi.cpp
kodi/integrationpluginkodi.json
kodi/kodi.cpp
kodi/kodi.h
kodi/translations/e7186890-99fa-4c5b-8247-09c6d450d490-de.ts
kodi/translations/e7186890-99fa-4c5b-8247-09c6d450d490-en_US.ts

Kodi: Use nymea icon for notifications and make notifications configurable

---

systemmonitor/integrationpluginsystemmonitor.json

System monitor: Disable unneeded caching of monitor states

---

keba/integrationpluginkeba.cpp
keba/integrationpluginkeba.h
keba/integrationpluginkeba.json
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-de.ts
keba/translations/9142b09f-30a9-43d0-9ede-2f8debe075ac-en_US.ts

Keba : Add support for wallboxes without energy meter (German Edition)

---

tado/tado.cpp

Tado: Fix encoding in login url

---

mystrom/integrationpluginmystrom.cpp

MyStrom: Fix a memory leak

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json

Shelly: Rework plugin to use CoAP instead of MQTT

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/shelly.pro
shelly/shellyjsonrpcclient.cpp
shelly/shellyjsonrpcclient.h

Shelly: Add support for the Shelly Plus 1[PM]

---

tasmota/integrationplugintasmota.cpp
tasmota/integrationplugintasmota.h
tasmota/integrationplugintasmota.json
tasmota/translations/d136e0c0-0cbf-4731-aabb-b2201088d6cb-en_US.ts

Tasmota: Add support for energy metering

---

keba/integrationpluginkeba.cpp
keba/integrationpluginkeba.json

Keba: Add a phase count setting to the Keba germany edition

---

tasmota/integrationplugintasmota.cpp
tasmota/integrationplugintasmota.h
tasmota/integrationplugintasmota.json
tasmota/translations/d136e0c0-0cbf-4731-aabb-b2201088d6cb-de.ts

Tasmota: Allow configuring the TelePeriod

---

pushnotifications/README.md
pushnotifications/integrationpluginpushnotifications.cpp
pushnotifications/integrationpluginpushnotifications.h
pushnotifications/integrationpluginpushnotifications.json
pushnotifications/translations/fdcea3b3-8d79-4fbb-8101-1ab45d71cedb-de.ts
pushnotifications/translations/fdcea3b3-8d79-4fbb-8101-1ab45d71cedb-en_US.ts

PushNotifications: Allow adding custom data to push notifications

---

bosswerk/integrationpluginbosswerk.cpp

Bosswerk: Improve discovery for setup

---

sma/integrationpluginsma.cpp
sma/sma.pro
sma/sunnywebbox.cpp
sma/sunnywebbox.h
sma/sunnywebboxdiscovery.cpp
sma/sunnywebboxdiscovery.h

SMA: Improve Sunny WebBox discovery

---

goecharger/README.md
goecharger/goecharger.pro
goecharger/goediscovery.cpp
goecharger/goediscovery.h
goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.h
goecharger/integrationplugingoecharger.json
goecharger/translations/a1dfca21-3f41-4a67-bc8c-c8b333411bd9-en_US.ts

go-eCharger:  Improve discovery and add API V2 support (Hardware V3) 

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for the Shelly TRV

---

nuki/integrationpluginnuki.cpp
nuki/integrationpluginnuki.json

Nuki: Update to new interface definition

---

keba/integrationpluginkeba.cpp

Keba: Finish action info after updating the according state

---

sgready/integrationpluginsgready.cpp

sgready: Fix set state value on mode changed

---

mystrom/integrationpluginmystrom.cpp
mystrom/integrationpluginmystrom.h
mystrom/translations/fc7f1a24-42a8-45ce-9ffb-136292eb0164-de.ts
mystrom/translations/fc7f1a24-42a8-45ce-9ffb-136292eb0164-en_US.ts

myStrom: Improve discovery mechanism

---

tempo/integrationplugintempo.cpp
tempo/tempo.cpp
tempo/translations/809bc4ca-d1cd-4279-9e0d-7324537ccb5a-en_US.ts

Tempo: Properly handle expired tokens

---

fronius/integrationpluginfronius.cpp
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-de.ts
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-en_US.ts

Fronius: Improve and translate error message for the user

---

mystrom/integrationpluginmystrom.cpp

MyStrom: Fix discovery for Swiss plugs

---

shelly/integrationpluginshelly.cpp

Shelly: Fix color state for rgbw2

---

fronius/froniussolarconnection.cpp
fronius/integrationpluginfronius.cpp

Fronius: Fix generating childs with multiple fronius connections

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for Shelly Flood, Smoke and Gas

---

tplink/integrationplugintplink.json

TP-Link: Disable caching for some states where it's not needed

---

mecelectronics/integrationpluginmecelectronics.cpp
mecelectronics/integrationpluginmecelectronics.json

MecMeter: Reduce some load by uncaching and rounding some states

---

bosswerk/integrationpluginbosswerk.cpp
fronius/integrationpluginfronius.cpp
goecharger/goediscovery.cpp
keba/kebadiscovery.cpp
meross/integrationpluginmeross.cpp
networkdetector/integrationpluginnetworkdetector.cpp
sma/speedwirediscovery.cpp
sma/sunnywebboxdiscovery.cpp
wakeonlan/integrationpluginwakeonlan.cpp

Clean up network device discovery replies due to mechanism update

---

goecharger/integrationplugingoecharger.cpp

go-e: Drop flooding useless debug print

---

sma/integrationpluginsma.json

SMA: Disable caching for frequently changing states

---

aqi/integrationpluginaqi.cpp
aqi/integrationpluginaqi.h
aqi/integrationpluginaqi.json

AQI: Update to new interface specification

---

bose/soundtouchtypes.h

Bose: Fix unitialized compiler warning

---

shelly/integrationpluginshelly.cpp

Shelly: Fix shelly 2.5 roller position

---

shelly/integrationpluginshelly.cpp

Shelly: Fix total energy consumed for 1 Plus PM

---

tplink/README.md

searched and located official TP link pages for these products. Some not available (discontinued?) and some only seem available in certain markets.

TP-Link: Added urls to read me

---

debian/control
debian/nymea-plugin-espuino.install.in
espuino/README.md
espuino/espuino.pro
espuino/integrationpluginespuino.cpp
espuino/integrationpluginespuino.h
espuino/integrationpluginespuino.json
espuino/meta.json
espuino/translations/5f8ba72b-d3fb-4efe-952d-a927bed20cfe-en_US.ts
nymea-plugins.pro

This adds support to control ESPuino - a software to build Rfid controlled music players.
I've introduced the plugin in https://forum.espuino.de/t/espuno-und-nymea-homeautomation/1354

New plugin: ESPuino

---

mqttclient/integrationpluginmqttclient.cpp
mqttclient/translations/27c58205-07c8-4482-85ad-b435387803a5-en_US.ts

MQTT client: Fix a crash when failing to connect to the internal broker

---

evbox/integrationpluginevbox.json

EVBox: Mark discovery as weak

---

goecharger/integrationplugingoecharger.cpp

go-e: Improve error messages

---

netatmo/integrationpluginnetatmo.json

Netatmo: Add min/max values for co2 sensors

---

evbox/evbox.pro
evbox/evboxdiscovery.cpp
evbox/evboxdiscovery.h
evbox/evboxport.cpp
evbox/evboxport.h
evbox/integrationpluginevbox.cpp
evbox/integrationpluginevbox.json

EVBox: Rework plugin to allow addressing multiple boxes on same bus

---

fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.h

Fronius: Set energy live states to 0 if not connected

---

powerfox/integrationpluginpowerfox.cpp
powerfox/integrationpluginpowerfox.h

powerfox: Set current power to 0 if not connected

---

netatmo/integrationpluginnetatmo.json

Netatmo: Add min/max values to pressure state

---

texasinstruments/integrationplugintexasinstruments.json

SensorTag: Add min/max to pressure state

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json

Add support for Shelly Plus 2PM

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for the Shelly Pro 3EM

---

philipshue/README.md
philipshue/hueremote.cpp
philipshue/hueremote.h
philipshue/huetapdial.cpp
philipshue/huetapdial.h
philipshue/integrationpluginphilipshue.cpp
philipshue/integrationpluginphilipshue.h
philipshue/integrationpluginphilipshue.json
philipshue/philipshue.pro
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-cs.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-da.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-de.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-en_US.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-es.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-fr.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-it.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-nl.ts
philipshue/translations/5f2e634b-b7f3-48ee-976a-b5ae22aa5c55-pt.ts

Philips Hue: Add support for Hue Tap Dial

---

tado/integrationplugintado.cpp

Tado: Suppress a warning when thermostat is off

---

fronius/integrationpluginfronius.cpp

Fronius: Fix PV power if there are multiple inverters

---

goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.json

go-e: Add possibility to control charging phases

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h

Shelly: Reconfigure CoAP on gen 1 shellies if they don't send any data

---

notifyevents/meta.json

Notify.Events: Fix a typo in meta.json

---

shelly/integrationpluginshelly.cpp

Shelly: Fix creation of children for the Plus 2PM

---

shelly/integrationpluginshelly.json

Update extendedclosable interfaces

---

bosswerk/integrationpluginbosswerk.cpp

Bosswerk: Don't poll the device when it's unreachable

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h
shelly/integrationpluginshelly.json
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-de.ts
shelly/translations/6162773b-0435-408c-a4f8-7860d38031a9-en_US.ts

Shelly: Add support for the Plus addon

---

shelly/integrationpluginshelly.cpp

Shelly: Mark devices offline on any polling network error

---

shelly/integrationpluginshelly.cpp

Shelly: Don't print password in debug logs

---

goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.h
goecharger/integrationplugingoecharger.json

go-eCharger: improve API V2 refreshing to reduce wallbox load

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json

Shelly plus addon

---

shelly/integrationpluginshelly.cpp

Shelly: Set discovery insensitive to upper / lower case

---

mqttclient/integrationpluginmqttclient.cpp
mqttclient/integrationpluginmqttclient.json

MqttClient: Add keep alive timeout parameter

---

keba/integrationpluginkeba.cpp
keba/kebaproductinfo.cpp
keba/kebaproductinfo.h

Keba: Fix parsing product information for BMW

---

eq-3/maxcube.cpp
eq-3/maxcube.h

EQ-3: Fix MaxCube building with latest gcc

---

elgato/integrationpluginelgato.cpp
eq-3/eqivabluetooth.cpp
eq-3/eqivabluetooth.h
eq-3/integrationplugineq-3.cpp
eq-3/integrationplugineq-3.h
eq-3/integrationplugineq-3.json
flowercare/integrationpluginflowercare.cpp
senic/integrationpluginsenic.cpp
texasinstruments/integrationplugintexasinstruments.cpp

latest firmware of those devices requires BT pairing

EQ-3: Add support for Bluetooth pairing

---

shelly/README.md
shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.json

Shelly: Add support for the PlusSmoke

---

unifi/integrationpluginunifi.cpp
unifi/integrationpluginunifi.h
unifi/integrationpluginunifi.json

Unifi: Fix connecting to the unifi controller on Unifi OS hosts

---

goecharger/goediscovery.cpp
goecharger/goediscovery.h
goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.h

go-e: Add zeroconf discovery support

---

fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.h

Fronius: Add support for S0 meters

---

keba/README.md
keba/integrationpluginkeba.cpp
keba/kebaproductinfo.cpp
keba/kebaproductinfo.h

Keba: Add support for P30 PV Edition

---

debian/control
debian/copyright

Update debian copyright

---

goecharger/goediscovery.cpp
goecharger/integrationplugingoecharger.cpp

go-E: Disable unsupported IPv6 discovery

---

kodi/integrationpluginkodi.cpp

Kodi: Fix unregister nonexisting plugin timer

---

networkdetector/integrationpluginnetworkdetector.cpp
networkdetector/integrationpluginnetworkdetector.h
networkdetector/integrationpluginnetworkdetector.json

NetworkDetector: Update to networkdevice interface

---

bosswerk/integrationpluginbosswerk.cpp
bosswerk/integrationpluginbosswerk.h
bosswerk/integrationpluginbosswerk.json

Bosswerk: Update to networkdevice interface

---

fronius/froniusdiscovery.cpp
fronius/froniusdiscovery.h
fronius/integrationpluginfronius.cpp
fronius/integrationpluginfronius.json
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-de.ts
fronius/translations/02319cfc-8b55-49ba-99bc-0588bbfab063-en_US.ts

Fronius: Update to networkdevice interface

---

goecharger/goediscovery.cpp
goecharger/goediscovery.h
goecharger/integrationplugingoecharger.cpp
goecharger/integrationplugingoecharger.json
goecharger/translations/a1dfca21-3f41-4a67-bc8c-c8b333411bd9-de.ts

go-eCharger: Update to networkdevice interface

---

meross/integrationpluginmeross.cpp
meross/integrationpluginmeross.h
meross/integrationpluginmeross.json

Meross: Update to networkdevice interface

---

wakeonlan/integrationpluginwakeonlan.cpp
wakeonlan/integrationpluginwakeonlan.json

WakeOnLan: Update to new network device discovery

---

shelly/integrationpluginshelly.cpp
shelly/integrationpluginshelly.h

Shelly: Add support for Gen3 hardware and fix #739

---

goecharger/integrationplugingoecharger.cpp

go-e: Update phase detection for charging and connected phases

---

everest/everest.cpp

EVerest: Fix invalid data handling from multiport charger

---

tado/integrationplugintado.cpp
tado/integrationplugintado.h
tado/integrationplugintado.json
tado/tado.cpp
tado/tado.h

Tado: Update account authentication to device code grant

---

meross/integrationpluginmeross.cpp

Meross: Improve datetime performance

---

everest/integrationplugineverest.cpp

EVerest: Fix crash on locahost monitor setup

---

debian/changelog
shelly/README.md
shelly/integrationpluginshelly.cpp

Shelly: Add support for Shelly Pro 3EM 400A model
